# Execute your favorite apps at launch
exec-once = ~/.config/hypr/xdg-portal-hyprland
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = waybar
exec-once = /usr/bin/hyprland-per-window-layout
exec-once = swaybg -m fill -i ~/.config/hypr/doomed_novosib-modified.jpg
exec = gsettings set org.gnome.desktop.interface gtk-theme "Dracula"   # for GTK3 apps
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
env = QT_QPA_PLATFORMTHEME,qt6ct   # for Qt apps
