windowrulev2 = tile, match:class:.*
windowrulev2 = opacity 1 1, match:class:.*
windowrulev2 = float, match:class:^(popup)$
windowrulev2 = float, match:title:^(context_menu)$
windowrulev2 = suppressevent maximize, match:class:.*



#windowrule = size 99% 90%, class:negative:(kitty)
#windowrule = move onscreen 0.5% 8%, class:negative:(kitty)

#windowrule = size 90% 90%, class:^(kitty)$
#windowrule = move onscreen 5% 8%, class:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
