windowrule = tile, class:.*
windowrule = opacity 1, class:.*
windowrule = float, class:^(popup)$ # Example using class
windowrule = float, title:^(context_menu)$ # Example using title
windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.



#windowrule = size 99% 90%, class:negative:(kitty)
#windowrule = move onscreen 0.5% 8%, class:negative:(kitty)

#windowrule = size 90% 90%, class:^(kitty)$
#windowrule = move onscreen 5% 8%, class:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
